[package]
name = "rust-bevy-udp-pra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renet = { version = "0.0.14", features = ["transport", "serde"] }
